#This is the multiplier which can shorten or lengthen potion effect durations, when you earn them by eating raw food. Default value is 0.8, meaning somewhat shorter durations on these difficulties.
#Range: 0.1 ~ 5.0
"Potion effect duration multiplier on easy and peaceful" = 0.8
#This is the multiplier which can shorten or lengthen potion effect durations, when you earn them by eating raw food. Default value is 1.0, meaning author-designed durations.
#Range: 0.1 ~ 5.0
"Potion effect duration multiplier on normal difficulty" = 1.0
#This is the multiplier which can shorten or lengthen potion effect durations, when you earn them by eating raw food. Default value is 1.3, meaning somewhat longer duration on these difficulties.
#Range: 0.1 ~ 5.0
"Potion effect duration multiplier on hard and hardcore" = 1.3

