
#Decorative Blocks Configs
[general]
	#Bonfire Activator, default: "minecraft:blaze_powder"
	"bonfire activator" = "minecraft:blaze_powder"
	#Disable thatch creation on shearing hay bale
	"thatch enabled" = true

