
["Dog Render"]
	#Enables the particle effect on Dire Level 30 dogs.
	enable_dire_particles = true
	#When enabled, dogs with points in pack puppy will have chests on their side.
	render_chest = true
	#If disabled will use the default minecraft wolf skin for all dog textures.
	enable_dt_textures = true
	#When enabled, dogs with points in wolf mount will have a saddle on.
	render_saddle = true
	#When enabled, Dogs will have wings when at level 5 pillow paw.
	render_wings = false
	#When enabled, Dogs will show injured texture while incapacitated.
	render_incapacitated_overlay = true
	#When sneaking, a part of the dog's name will be rendered with a certain color
	#and the length of the part is based on the health percentage the dog has left
	render_health_in_name = true
	#Render a universal dog inventory access button in your inventory gui.
	#If this is turned off, you can still access the button via the dog's
	#GUI in Talents > Pack Puppy.
	dog_inv_button_in_inv = true
	#If the defeault incapacitated texture proof too much graphic.
	#You can substitute this friendlier texture instead.
	render_incap_txt_less_graphic = false
	#Render dogs' name whose owner is not you with different color.
	render_diffowner_name_different = true
	#Attempt to block third parties from rendering overlays which may conflict
	#with DT's built-in tag. It is recommended that this be achieved via the target third-party's
	#configurations if they have the option to disable nametag overlay for certain mobs
	#(Which they should). This option should only be used as the last resort.
	block_third_party_nametag = false
	#By defeault, the CLASSICAL skin directly references the
	#in-game vanilla wolf texture for rendering. Turning this on
	#will allow a copy of the vanilla wolf texture provided by the mod to be used instead.
	use_provided_copy_for_classical = false
	#Show a fun icon on world loading screen.
	world_load_icon = true
	#Determine if dogs will render their armor.
	render_armor = true

