
#Flood settings
[Flood]
	#The chance the water gets converted (1.0 = 100%, 0.5 = 50%) [default: 0.0625 = 6.25%]
	#Range: 0.0 ~ 1.0
	convertChance = 0.0625
	#The water level from which it will try to convert [1 = lowest puddle, 8 = source] [default: 4]
	#Range: 1 ~ 8
	waterLevelToConvert = 7
	#Stop water from turning into source above sea level [default: true]
	seaLevelProtection = true
	#The dimensions in which the mod affects the water during rain [default: ["minecraft:overworld"]]
	dimensions = ["minecraft:overworld"]
	#Allow the mod to place water when no water is present [default: true]
	canPlaceWater = true
	#The chance the water gets placed (1.0 = 100%, 0.5 = 50%) [default: 0.0625 = 6.25%]
	#Range: 0.0 ~ 1.0
	placeChance = 0.0625
	#The water level to place when no water is present [0 = source, 1 = lowest puddle, 15 = source] [default: 1]
	#Range: 0 ~ 15
	levelToPlace = 1

