
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_end", -0.1, "MC"], ["minecraft:the_nether", 1.0, "MC"]]
	#Overrides existing dimension temperatures & offsets
	#Also overrides temperatures of all biomes in the dimension
	"Dimension Temperatures" = []

#Format: [["biome_1", tempLow, tempHigh, *units], ["biome_2", tempLow, tempHigh, *units]... etc]
#temp-low: The temperature of the biome at midnight
#temp-high: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding existing biome temperatures & offsets.
	"Biome Temperatures" = [["minecraft:savanna_plateau", 76.0, 98.0, "F"], ["minecraft:taiga", 44.0, 62.0, "F"], ["minecraft:eroded_badlands", 88.0, 120.0, "F"], ["minecraft:savanna", 70.0, 95.0, "F"], ["minecraft:swamp", 72.0, 84.0, "F"], ["minecraft:bamboo_jungle", 76.0, 87.0, "F"], ["minecraft:frozen_peaks", 15.0, 33.0, "F"], ["minecraft:old_growth_spruce_taiga", 48.0, 62.0, "F"], ["minecraft:snowy_beach", 38.0, 52.0, "F"], ["minecraft:deep_dark", 63.0, 63.0, "F"], ["minecraft:warm_ocean", 67.0, 76.0, "F"], ["minecraft:windswept_forest", 48.0, 66.0, "F"], ["minecraft:jungle", 76.0, 87.0, "F"], ["minecraft:snowy_slopes", 24.0, 38.0, "F"], ["minecraft:stony_shore", 50.0, 64.0, "F"], ["minecraft:soul_sand_valley", 53.0, 53.0, "F"], ["minecraft:old_growth_birch_forest", 58.0, 72.0, "F"], ["minecraft:desert", 48.0, 115.0, "F"], ["minecraft:snowy_taiga", 19.0, 48.0, "F"], ["minecraft:badlands", 84.0, 120.0, "F"], ["minecraft:deep_frozen_ocean", 56.0, 65.0, "F"], ["minecraft:river", 60.0, 70.0, "F"], ["minecraft:old_growth_pine_taiga", 48.0, 62.0, "F"], ["minecraft:windswept_savanna", 67.0, 90.0, "F"], ["minecraft:wooded_badlands", 80.0, 108.0, "F"]]

["Block Temperature"]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range (max 7)>, <*true/false: falloff>, <*max effect>, <*predicates>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: the temperature of the block, in Minecraft units
	#falloff: the block is less effective as distance increases
	#max effect: the maximum temperature change this block can cause to a player (even with multiple blocks)
	#predicates: the state that the block has to be in for the temperature to be applied (lit=true for a campfire, for example).
	#Multiple predicates can be used by separating them with commas (i.e: "lit=true,waterlogged=false")
	BlockTemps = [["minecraft:soul_fire", -0.476, 7, true, 0.8], ["minecraft:fire", 0.476, 7, true, 0.8], ["minecraft:magma_block", 0.5, 3, true, 0.6], ["minecraft:soul_campfire", -0.476, 3, true, 0.6, "lit=true"], ["minecraft:ice", -0.15, 4, true, 0.5], ["minecraft:packed_ice", -0.25, 4, true, 1.0], ["minecraft:blue_ice", -0.35, 4, true, 1.0]]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7

[Misc]
	#The amount of temperature normalization from being deep underground
	#0.0 = no insulation, 1.0 = full insulation
	#Range: 0.0 ~ 1.0
	"Cave Insulation Strength" = 1.0

#Format: [season-start, season-mid, season-end]
#Applied as an offset to the world's temperature
["Season Temperatures"]
	Summer = [0.4, 0.6, 0.4]
	Autumn = [0.2, 0, -0.2]
	Winter = [-0.4, -0.6, -0.4]
	Spring = [-0.2, 0, 0.2]

[Hearth]
	#How strong the hearth is
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.5
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "#minecraft:leaves"]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

